- name: hello world
  #hosts: web
  hosts: local
  connection: local
  tasks:
    - name: print hello world
      ansible.builtin.debug:
        msg: "Hello world"

- name: 2nd playbook
  hosts: local
  connection: local
  tasks:
    - name: print 2nd playbook
      ansible.builtin.debug:
        msg: "2nd playbook details"
