- name: play level variables
  hosts: local
  connnection: local
  vars:
    Courese: "Devops with AWS"
    Duration: 140+hrs
    Trainer: "Sivakumar"
  Tasks:
    - name: print variables
      ansible.builtin.debug:
        msg: "Course is {{Courese}}, Trainer is: {{Trainer}}"
