- name: Task level variables
  hosts: local
  connection: local
  tasks:
    - name: print vairables
      vars:
        course: Ansible
      ansible.builtin.debug:
        msg: "Course is {{course}}"
