- name: ansible command vs shell
  hosts: local
  connection: local
  tasks:
    - name: command module test
      #ansible.buitlin.command: cat /etc/passwd | grep root
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: users_output

    - name: print the users_output
      ansible.builtin.debug:
        msg: "{{users_output}}"

    - name: files print
      #ansible.buitlin.command: cat /etc/passwd | grep root
      ansible.builtin.shell: ls -ltr > files.txt
      register: files_output

    - name: print the files output
      ansible.builtin.debug:
        msg: "{{files_output}}"
